# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# 'C:\sr\config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- http-types-0.11
- regexpr-0.5.4
- mtlparse-0.1.4.0
- pandoc-2.1.1
- pandoc-types-1.17.3.1
resolver: lts-11.10
